-- Practice chapters 9-11 of SQL book (Joan Casteels)
-- Oracle SQL 12c

-- SQL Data definition commands

-- Create database
-- create database testdb;

-- Create function to check if email is present in db
-- create or replace function email_exists(email in varchar2)
-- return number
-- is
--   v_count number;
-- begin
--   select count(*) into v_count
--   from users
--   where email = email;
--
--   if v_count > 0 then
--     return 1; -- Email exists
--   else
--     return 0; -- Email does not exists
--   end if;
-- end;

-- Create table
-- create if not exists table users (
  -- id number(10) not null primary key,
  -- name varchar2(50) not null,
  -- email varchar2(100) not null,
  -- created_at date default sysdate,
  -- updated_at date default sysdate
-- );

-- Sequences are objects like tables
create sequence users_seq
  start with 1
  increment by 1
  minvalue 1
  maxvalue 99999999;

create table users (
  id number default users_seq.nextval primary key
);

-- Create table with auto increment
create table users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

create view contact as
  select * from users;


